---
galaxy_info:
  role_name: dagu
  author: Marcus Ã–sterlund
  description: Deploy and manage Dagu workflow scheduler
  company: Webmarcus AB
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - dagu
    - workflow
    - scheduler
    - orchestration
    - automation
    - dag

dependencies: []
